@Harvey-Tsai Harvey-Tsai committed 11 minutes ago
Azure/iot-plugandplay-models pull request #179
Opened 2021-04-13 05:28 UTC by Harvey-Tsai

### Company Info

Advantech 

Company website: www.advantech.com
GitHub : https://github.com/Harvey-Tsai/iot-plugandplay-models

### IoT Plug and Play Device Info

ESRP-CSS-UNO1372: https://www.advantech.com/products/05dd6ca3-f058-4c73-824e-dc9143898a45/esrp-css-uno1372/mod_0fa58890-1962-4901-83b9-1e08eada3bb3
OS & Arch : Ubuntu 18.04 & x86_64

ESRP-CSS-UNO2271: https://www.advantech.com/products/05dd6ca3-f058-4c73-824e-dc9143898a45/esrp-css-uno2271/mod_c0ddbe2f-5c75-486d-b2e4-312d89c04649
OS & Arch : Ubuntu 18.04 & x86_64

ESRP-CSS-UNO2372: https://www.advantech.com/products/05dd6ca3-f058-4c73-824e-dc9143898a45/esrp-css-uno2372/mod_0ea177e9-c4a7-44c6-9342-a026cecc871f
OS & Arch : Ubuntu 18.04 & x86_64

ESRP-CSS-UNO2484: https://www.advantech.com/products/05dd6ca3-f058-4c73-824e-dc9143898a45/esrp-css-uno2484/mod_98d0b774-c73f-4b70-9f79-919e7fc24ce0
OS & Arch : Ubuntu 18.04 & x86_64

### Model Submission Goals

- Device certification
- Presence in the [Certified Device catalog](https://devicecatalog.azure.com/)
- IoT Central integration
- Custom solution

### Code Owners & Reserved Names

Code Owners : Harvey.Tsai
mail: Harvey.Tsai@advantech.com.tw

2021-04-13 16:21 UTC, rido-min requested changes
provide a more descriptive `displayName` for each interface

2021-04-13 16:21 UTC, rido-min commented on dtmi/advantech/esrp_uno1372-2.json
> +  "displayName": "ADVANTECH device Model",
provide a more descriptive `displayName`

2021-04-13 16:21 UTC, rido-min commented on dtmi/advantech/esrp_uno2484-2.json
> +  "displayName": "ADVANTECH device Model",
provide a more descriptive `displayName`

2021-04-13 16:21 UTC, rido-min commented on dtmi/advantech/esrp_uno2271-2.json
> +  "displayName": "ADVANTECH device Model",
provide a more descriptive `displayName`

2021-04-14 01:47 UTC, Harvey-Tsai commented on dtmi/advantech/esrp_uno1372-2.json
> +  "displayName": "ADVANTECH device Model",
"displayName": "ESRP_UNO1372",

2021-04-14 01:47 UTC, Harvey-Tsai commented on dtmi/advantech/esrp_uno2484-2.json
> +  "displayName": "ADVANTECH device Model",
"displayName": "ESRP_UNO2484",

2021-04-14 01:47 UTC, Harvey-Tsai commented on dtmi/advantech/esrp_uno2271-2.json
> +  "displayName": "ADVANTECH device Model",
"displayName": "ESRP_UNO2271",

2021-04-14 15:52 UTC, rido-min approved these changes

2021-04-14 15:53 UTC, merged