Add VECOW SPC-7000 model
Azure/iot-plugandplay-models pull request #225
Opened 2021-04-23 09:04 UTC by WayneHou118

**Company Info**
VECOW
http://www.vecow.com/dispPageBox/vecow/VecowHp.aspx?ddsPageID=VECOW_EN
**IOT Plug and Play Device Info**
SPC-7000

2021-04-23 18:19 UTC, rido-min approved these changes

2021-04-23 19:44 UTC, rido-min requested changes
fix filename issue

2021-04-23 19:44 UTC, rido-min commented on dtmi/vecow/spc_7000.json
> +    "@id": "dtmi:VECOW:SPC_7000;1",
file name should include the version from the root id

2021-04-27 05:31 UTC, WayneHou118 commented
Upload the correct file name with revision info.

2021-04-27 13:52 UTC, rido-min approved these changes

2021-04-27 13:52 UTC, merged