Add Renesas RX65N Cloud Kit Model
Azure/iot-plugandplay-models pull request #251
Opened 2021-05-06 09:02 UTC by TatsuyaOgawanx

### Thank you for contributing to the Azure IoT Plug and Play Models repository

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

The repository pipeline will ensure minimum validation of incoming DTDL models.  

- PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet#device-model-repository-client) CLI.

## Requested info template for model(s) submission

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve Plug and Play.

:star2: Please replace the markdown comment examples with your own values.

### Company Info
Renesas Electronics Corporation

### IoT Plug and Play Device Info
Devkit sample

### Model Submission Goals
IoT Central integration

### Code Owners & Reserved Names
@TatsuyaOgawanx

2021-05-06 18:54 UTC, rido-min approved these changes

2021-05-06 18:58 UTC, rido-min commented
@TatsuyaOgawanx  can you update this PR with the changes from `main` ? (next time you can enable contributors to update as described [here](https://docs.github.com/en/enterprise-server@2.21/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork))

2021-05-06 22:35 UTC, rido-min requested changes
update from base branch

2021-05-07 00:06 UTC, TatsuyaOgawanx commented
I updated from base branch.

2021-05-07 16:05 UTC, rido-min approved these changes

2021-05-07 16:05 UTC, merged