Add most of the remaining CloudRail files
Azure/iot-plugandplay-models pull request #296
Opened 2021-06-02 15:00 UTC by PatrickStoklasa

2021-06-07 22:42 UTC, rido-min commented
@PatrickStoklasa  can you update this PR to be updated from the base branch?

2021-06-08 14:53 UTC, rido-min requested changes
update from base branch

2021-06-08 15:49 UTC, PatrickStoklasa commented
Updated with the latest commits from main branch

2021-06-08 22:37 UTC, rido-min approved these changes

2021-06-09 15:14 UTC, merged