Update Advantech MIC-710AIX interface
Azure/iot-plugandplay-models pull request #321
Opened 2021-06-30 15:31 UTC by paul53huang

### Company Info

- Company name: Advantech
- Company website: https://www.advantech.com/
- GitHub presence: https://github.com/ADVANTECH-Corp/

### PnP Device Info

- Product website: https://www.advantech.tw/products/9140b94e-bcfa-4aa4-8df2-1145026ad613/mic-710aix/mod_4682ea39-3903-4fa2-93a0-a075a295343d

### Model Submission Goals
- Device certification

### Code Owners & Reserved Names
- @paul53huang

2021-07-01 10:32 UTC, rido-min requested changes
@paul53huang  can you update this PR from the base branch?

I'm missing the `displayName` property, all other Advantech interfaces have it.

2021-07-02 02:12 UTC, paul53huang commented
Hi @rido-min thanks for reminding to add the displayName.
I just push a new version for it. 
Appreciate!

2021-07-02 13:31 UTC, rido-min approved these changes

2021-07-05 23:14 UTC, rido-min approved these changes

2021-07-05 23:14 UTC, merged