Add a new JSON
Azure/iot-plugandplay-models pull request #370
Opened 2021-10-01 05:09 UTC by hy-tsai-brickcom

### Thank you for contributing to the Azure IoT Plug and Play Models repository

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

The repository pipeline will ensure minimum validation of incoming DTDL models.  

- PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine) command line tool.

## Requested info template for model(s) submission

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve Plug and Play.

:star2: Please replace the markdown comment examples with your own values.

### Company Info

### IoT Plug and Play Device Info

### Model Submission Goals

### Code Owners & Reserved Names

2021-10-01 14:41 UTC, rido-min requested changes
Seems you missed the file extension, it should be `.json`.

Also, as this is the first submission to claim the namespace `brickcom`, can you update the PR template?

2021-10-04 03:29 UTC, hy-tsai-brickcom commented
thanks for your reminder

2021-10-04 07:07 UTC, hy-tsai-brickcom commented
### Company Info
**Company name**
Brickcom Corporation
**Company website**
https://www.brickcom.com
**GitHub presence**
https://github.com/hy-tsai-brickcom
**Other**
###IoT Plug and Play Device Info
**Product website**
https://www.brickcom.com
**Other**
###Model Submission Goals
Device certification
Presence in the Certified Device catalog
###Code Owners & Reserved Names

2021-10-04 16:12 UTC, rido-min approved these changes

2021-10-04 16:18 UTC, merged