Improvements in readme to allow direct usage of tool commands
Azure/iot-plugandplay-models pull request #465
Opened 2022-05-19 13:03 UTC by josesimoes

# Changes:
- Remove leading `>` from bash sections.
- Move comments in the bash sections outside of it.

# Motivation
- I was following the readme and hit the copy icon that shows on mouse over (as usual) 
![image](https://user-images.githubusercontent.com/1881520/169299136-b82390a1-299a-48dc-ab68-236d5c0fd230.png)
to then realize that it includes a leading `> `  to mimic the prompt. 
Some of these sections also include a comment at the top. 
Both of these make the commands unusable when trying to use the speedy access of clicking on copy icon to just paste it at the prompt.
This PR addresses that by cleaning up the commands and make them usable with the shortcut.

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

2022-05-19 22:26 UTC, rido-min requested changes
can you update this PR with the latest from the main branch?

2022-05-19 23:04 UTC, josesimoes commented
@rido-min just rebased it

2022-05-20 00:18 UTC, digimaun submitted a review, later dismissed

2022-05-20 00:20 UTC, digimaun commented on README.md
> +The default `--local-repo` value is the current directory. Be sure to specifiy the root for `--local-repo`.
```suggestion
The default `--local-repo` value is the current directory. Be sure to specify the root for `--local-repo`.
```

2022-05-20 00:22 UTC, digimaun approved these changes

2022-05-20 00:27 UTC, merged