Murata IoT Device Models
Azure/iot-plugandplay-models pull request #545
Opened 2023-08-21 19:40 UTC by xlinmurata

### Thank you for contributing to the IoT Plug and Play Models repository

:memo: Please review this checklist before submission

- [ ] :eyes: The models submitted in this PR follow the [DTDL Naming Guidelines](https://github.com/Azure/iot-plugandplay-models-tools/wiki/DTDL-Naming-Guidelines) for contributing to this repository.
- [ ] 🕵️I have validated the models locally using the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine) command line tool.
- [ ] ❗ I understand once the PR is approved, the models are considered immutable: any edits will require to submit new files.
- [ ] ✨ When creating a new top level `dtmi:namespace`, I have completed the [PR Info Template](#pr-info-template) below.

:zap: PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).

## PR Info Template

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve the _IoT Plug and Play_ ecosystem.

👇: Please replace the markdown comment examples with your own values.

### Company Info

> Info identifying your company (if applicable).

### IoT Plug and Play Device Info
> Info identifying your device.

### Model Submission Goals

> Info related to broader submission goals.  

### Code Owners & Reserved Names

> Indicates GitHub alias entries to be added to the repo `CODEOWNERS` for the incoming model namespace. The codeowner is expected to be involved in subsequent DTDL model submissions against the same namespace.

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

2023-08-21 20:10 UTC, xlinmurata commented
Hi, 

I am trying to add the device models for my company("Murata"). It is my first project on github, I don't have any idea on what failed and why, can you please explain?
Thanks,
Xlin

2023-08-21 20:25 UTC, rido-min commented
@xlinmurata thanks for submitting a new model.

This submission is failing because some files do not have the `@context` specifier

https://github.com/Azure/iot-plugandplay-models/actions/runs/5930729946/job/16081218156?pr=545#step:3:582

2023-08-21 22:13 UTC, xlinmurata commented
I updated files. and now what I need to do next?

2023-08-21 22:30 UTC, rido-min commented
> I updated files. and now what I need to do next?

commit and push to the same branch

2023-08-23 16:41 UTC, rido-min requested changes
the validation still fails.

You can validate locally by using dmr-client as described in https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine

2023-08-23 16:41 UTC, rido-min commented on dtmi/murata/demo_iot-1.json
> +            "@id": "dtmi:murata:b_u585i_iot02a:standard_fw:std_comp;3",
I dont think you need this @id, but if you do it should follow the root id.

https://github.com/Azure/iot-plugandplay-models-tools/wiki/Resolution-Convention#unique-id-elements

2023-08-24 20:34 UTC, xlinmurata commented
I have a change request, I have made/commit/push the change and replied with dmr-client validation result.  is there anything I need to do to trigger the PR? sorry for all the questions as I am a newbie.

2023-08-24 20:40 UTC, merged