PR To Main from local to include RPI4 into IoT-Plug-And-Play
Azure/iot-plugandplay-models pull request #62
Opened 2020-12-08 19:30 UTC by fmendoz7

### Thank you for contributing to the Azure IoT Plug and Play Models repository

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

The repository pipeline will ensure minimum validation of incoming DTDL models.  

- PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet#device-model-repository-client) CLI.

## Requested info template for model(s) submission

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve Plug and Play.

:star2: Please replace the markdown comment examples with your own values.

### Company Info

Raspberry Pi
https://www.raspberrypi.org/

### PnP Device Info

https://www.raspberrypi.org/products/raspberry-pi-4-model-b/?resellerType=home
Linux, Ubuntu 20.04 LTS
ARM64 Processor Architecture
128000000 kilobytes total storage
4000000 kilobytes total memory

### Model Submission Goals
 
Presence in certified device catalog (https://devicecatalog.azure.com/)
Custom Solution

### Code Owners & Reserved Names

@fmendoz7

2020-12-08 19:51 UTC, rido-min requested changes
The interface is using a reserved word in the id, as described [here](https://github.com/Azure/iot-plugandplay-models/blob/main/pr-reqs.md#reserved-words)

Also, this interface seems the same as DeviceInfo.

Is this submission associated with the raspberrypi team?

2020-12-10 17:23 UTC, fmendoz7 commented
Hi. This submission is not associated with the RP team, rather, this is a project under Intel Corporation wanting to use RPI4 in the Azure device marketplace for a project, but not able to find such model

2020-12-10 18:11 UTC, rido-min requested changes
There are still some issues in this PR.
- The `@id` used should not includes reserved words (as azure)
- I'd suggest to use more explicit ids than `dtmi:rpi4`
- There are unwanted files in the PR ( in the `,vs/` folder )

2020-12-10 18:34 UTC, fmendoz7 commented
Apologies, but I am a little confused as to how I am failing the validate-dtdl-models check. The @id for rpi4-1.json is "dtmi:raspberrypi:rpi4;1", but the presence of the reserved keyword "azure" is not on that file

2020-12-10 18:54 UTC, rido-min commented on dtmi/azure/devicemanagement/dtmi/azure/devicemanagement/rpi4-1.json
> +  "@id": "dtmi:azure:DeviceManagement:rpi4;1",
dont use `dtmi:azure` prefix

2020-12-10 18:56 UTC, rido-min commented
I see the `azure` prefix in `dtmi/azure/devicemanagement/dtmi/azure/devicemanagement/rpi4-1.json`

Please note there is also an issue in the path (seems dtmi/ is dupe).

I'd suggest to use the `dmr-client` to validate locally before publishing, and to copy the files to the right location.
https://github.com/Azure/iot-plugandplay-models#install-dmr-client

2021-01-11 21:32 UTC, rido-min commented
@fmendoz7 do you have any plans to update this PR? if not, can you please close it?

2021-01-24 05:10 UTC, closed without merging